"""DNA landing tests — validate + land a 23andMe-format genotype export, never its content.

DNA is not a time-series reading; `dna.land` validates the genotype-table shape and
lands the file in the gitignored dropzone, surfacing only the variant COUNT (never the
genotype calls). These tests run against a SYNTHETIC 23andMe-format fixture.
"""

import zipfile

import pytest

from scripts.ingest import dna

# A minimal real-shape 23andMe raw export: a `#`-comment header over tab-separated
# rsid/chromosome/position/genotype rows (incl. an internal `i` id, an MT single-call,
# and an `--` no-call — the genotype-call variants the validator must accept).
_HEADER = [
    "# This data file generated by 23andMe at: Mon Jan 01 00:00:00 2024",
    "# rsid\tchromosome\tposition\tgenotype",
]
_ROWS = [
    "rs4477212\t1\t82154\tAA",
    "rs3094315\t1\t752566\tAG",
    "rs3131972\t1\t752721\tGG",
    "i5000023\tMT\t16519\tC",
    "rs12345\tX\t100000\t--",
]


def _write_dna_txt(path, rows=_ROWS):
    path.write_text("\n".join([*_HEADER, *rows]) + "\n")


def test_land_raw_txt_counts_variants_and_lands(tmp_path):
    """A raw .txt export lands under its basename with the correct variant count."""
    src = tmp_path / "genome_Full.txt"
    _write_dna_txt(src)
    dna_root = tmp_path / "raw"
    result = dna.land(src, dna_root)
    assert result["variants"] == 5            # the 5 genotype rows; the 2 `#` header lines excluded
    assert result["name"] == "genome_Full.txt"
    assert (dna_root / "genome_Full.txt").exists()
    assert result["path"] == dna_root / "genome_Full.txt"


def test_land_zip_extracts_only_the_genotype_member(tmp_path):
    """The genotype .txt is extracted from a zip; resource forks + non-genotype .txt are skipped."""
    src = tmp_path / "23andme_export.zip"
    with zipfile.ZipFile(src, "w") as zf:
        zf.writestr("__MACOSX/._junk", "resource fork")
        zf.writestr("readme.txt", "not a genotype file at all")
        zf.writestr("genome_v5.txt", "\n".join([*_HEADER, *_ROWS]) + "\n")
    dna_root = tmp_path / "raw"
    result = dna.land(src, dna_root)
    assert result["variants"] == 5
    assert (dna_root / "genome_v5.txt").exists()
    assert not (dna_root / "readme.txt").exists()   # the non-genotype member was NOT landed


def test_land_non_genotype_txt_raises(tmp_path):
    """A .txt that is not a genotype table fails loud — a wrong file is never silently landed."""
    src = tmp_path / "notes.txt"
    src.write_text("just some notes\nnothing genetic here\n")
    raw = tmp_path / "raw"
    with pytest.raises(ValueError):
        dna.land(src, raw)
    assert not list(raw.glob("*.txt"))   # nothing landed when validation fails


def test_land_zip_without_genotype_member_raises(tmp_path):
    """A zip carrying no genotype .txt fails loud."""
    src = tmp_path / "empty.zip"
    with zipfile.ZipFile(src, "w") as zf:
        zf.writestr("readme.txt", "no genotype rows here")
    with pytest.raises(ValueError):
        dna.land(src, tmp_path / "raw")


def test_land_is_idempotent_overwrite(tmp_path):
    """Re-landing the same export overwrites in place — no duplicate file, same count."""
    src = tmp_path / "g.txt"
    _write_dna_txt(src)
    dna_root = tmp_path / "raw"
    first = dna.land(src, dna_root)
    second = dna.land(src, dna_root)
    assert first["variants"] == second["variants"] == 5
    assert len(list(dna_root.glob("*.txt"))) == 1


def test_land_return_surfaces_counts_only_not_content(tmp_path):
    """The return carries exactly {path, variants, name} — no genotype calls surface (privacy)."""
    src = tmp_path / "g.txt"
    _write_dna_txt(src)
    result = dna.land(src, tmp_path / "raw")
    assert set(result) == {"path", "variants", "name"}
    assert isinstance(result["variants"], int)
